GET http://localhost:3000/sn-users/

###
GET http://localhost:3000/sn-users/shannon1

###
POST http://localhost:3000/sn-users/login/
Content-Type: application/json

{
    "username": "shannon1",
    "password": "shannon123"
}

###
Get http://localhost:3000/dj_news/searchTerm

###
GET http://localhost:3000/sn-users/logout

###

PATCH http://localhost:3000/sn-users/shannon1
Content-Type: application/json

{
    "password": "shannon123"
}

###

DELETE http://localhost:3000/sn-users/heyarnold
