GET http://localhost:3000/sn-users/

###
Get http://localhost:3000/dj_news/searchTerm

###
POST http://localhost:3000/sn-users/
Content-Type: application/json

{
    "name": "David",
    "email": "sBrown@gmail.com",
    "password": "SBrown$@@20"
}


